### ISSUE TITLE
Shadows on notifications

### ISSUE THREAD

**Issue by somepaulo** [kaanginam/expandable-notifications#10]
This extension adds shadows to notifications in the Notification Center. Disabling it removes the shadows.
You can run `notify-send -t 3000 -i face-smile "The First Notification" "Hello <b>World</b>"` to generate a test notification.

![Screenshot from 2023-05-16 17-10-54](https://github.com/kaanginam/expandable-notifications/assets/15643750/a4f34d12-ddb8-4c57-8d0a-c1e23d409aa0)

**Comment by kaanginam** [comment]
Hey, if this is something that needs to be removed I'll look at it. 

The extension doesn't add the shadows but it changes the class of the Notification to be that of the extension you see on the screen. 

If that has shadows, that's probably why the extension is displaying them.

Thanks for the issue!

**Comment by somepaulo** [comment]
I think this is due to what's described on lines `144-146` of the extension - using the `NotificationBanner` instead of the `NotificationMessage` class. Since banners do have shadows, they must come from that class.

It's easy to fix by adding a custom class to the banner with `message.add_style_class_name('expandable');`, and a `stylesheet.css` file with `.expandable{.box-shadow: none !important;}`.

**Comment by somepaulo** [comment]
I fixed this in #11

**Comment by kaanginam** [comment]
> I think this is due to what's described on lines `144-146` of the extension – using the `NotificationBanner` class instead of the `NotificationMessage` one. Since banners do have shadows, they must come from that class.
> 
> It's easy to fix by adding a custom class to the banner with `message.add_style_class_name('expandable');`, and a `stylesheet.css` file with `.expandable{.box-shadow: none !important;}`.

That is what I was trying to say, just did not have the time for the specifics - thanks for the PR! It is now merged and waiting for review on the extensions page.
